IDPPred/urls.py
from django.urls import path
from IDPPred import views

app_name = 'IDPPred'
urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('about', views.about, name='about'),
    path('help', views.help, name='help'),
    path('sources', views.sources, name='sources'),
]

IDPPred_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from IDPPred import views

urlpatterns = [
    path('', views.index, name='index'),
    path('IDPPred/', include('IDPPred.urls')),
    path('admin/', admin.site.urls),
]

IDPPred/models.py
from django.db import models

# Create your models here.

IDPPred/forms.py
from django import forms

class SequenceForm(forms.Form):
    Sequence = forms.CharField(max_length=1000)

IDPPred/views.py
from django.shortcuts import render
from django.http import HttpResponse
from IDPPred.forms import SequenceForm
from IDPPred.pytorch_models import Seq_model, Residue_model, pre_processing
import numpy as np
import torch
from django.templatetags.static import static
import os


# Create your views here.
def index(request):
    context_dict = {}
    form = SequenceForm()
    if request.method == "POST":
        form = SequenceForm(request.POST)

        if form.is_valid():
            sequence = form.cleaned_data.get("Sequence")

            encoded_seq, all_onehot = pre_processing(sequence)

            seq_model = Seq_model()

            path = os.path.join(os.path.dirname(os.path.dirname(__file__)),'static/weights/PROT_CNNcustom_weights.pth')
            seq_model.load_state_dict(torch.load(path))

            seq_preds = seq_model.get_predictions(encoded_seq)

            res_model = Residue_model()

            path = os.path.join(os.path.dirname(os.path.dirname(__file__)),'static/weights/VEC_LSTMcustom_weights.pth')

            res_model.load_state_dict(torch.load(path))

            res_preds = []
            for subseq in all_onehot:
                print(subseq)
                res_pred = res_model.get_predictions(subseq)
                res_preds.append(res_pred)

            if (seq_preds.item() > 0.75):
                seq_data = {'sequence':sequence, 'class': 'Disordered', 'prediction':round(seq_preds.item()*100,2),'high':True}
            elif (seq_preds.item() > 0.5):
                seq_data = {'sequence':sequence, 'class': 'Disordered', 'prediction':round(seq_preds.item()*100,2),'med':True}
            elif (seq_preds.item() < 0.25):
                seq_data = {'sequence':sequence, 'class': 'Fully Ordered', 'prediction':round(seq_preds.item()*100,2), 'verylow':True}
            elif (seq_preds.item() < 0.5):
                seq_data = {'sequence':sequence, 'class': 'Fully Ordered', 'prediction':round(seq_preds.item()*100,2), 'low':True}

            print(len(sequence))
            print(len(res_preds))
            print(res_preds)
            res_counter = 0
            counter = 0
            letters = []
            for letter in sequence:
                if counter > 6 and counter < len(sequence)-7:
                    if (res_preds[res_counter].item() > 0.75):
                        letter_data = {'residue':letter, 'prediction': res_preds[res_counter].item(), 'high':True}
                    elif (res_preds[res_counter].item() > 0.5):
                        letter_data = {'residue':letter, 'prediction': res_preds[res_counter].item(), 'med':True}
                    elif (res_preds[res_counter].item() < 0.25):
                        letter_data = {'residue':letter, 'prediction': res_preds[res_counter].item(), 'verylow':True}
                    elif (res_preds[res_counter].item() < 0.5):
                        letter_data = {'residue':letter, 'prediction': res_preds[res_counter].item(), 'low':True}

                    letters.append(letter_data)
                    res_counter += 1
                else:
                    print(counter)
                    letter_data = {'residue':letter, 'prediction': 0, 'neutral':True}
                    letters.append(letter_data)

                counter += 1
            context_dict["letters"] = letters
            context_dict['sequence_data'] = seq_data
        
        return render(request, 'IDPPred/index.html', context=context_dict)

    context_dict["form"] = form
    context_dict["GET"] = "GET"
    return render(request, 'IDPPred/index.html', context=context_dict)

def about(request):
    context_dict = {}
    return render(request, 'IDPPred/about.html', context=context_dict)

def help(request):
    context_dict = {}
    return render(request, 'IDPPred/help.html', context=context_dict)

def sources(request):
    context_dict = {}
    return render(request, 'IDPPred/sources.html', context=context_dict)

templates/IDPPred/about.html
{% extends 'IDPPred/base.html' %}
{% load staticfiles %} 

{% block title_block %}
    About
{% endblock %}

{% block nav %}
    <span class="nav">
        <ul class="nav">
            <li class="picnav"><img class="nav" src="{% static 'images/logo3.png' %}" alt="Logo" /></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:index' %}">Home</a></li>
            <li class="nav" style="text-decoration: underline"><a class="nav active" href="{% url 'IDPPred:about' %}">About</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:help' %}">Help</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:sources' %}">Sources</a></li>
        </ul>
    </span>
    {% endblock %}


{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        hey there partner! <br />
    </div>
    <img src="{% static 'images/logo.png' %}" alt="Logo" />
    <div>
        <a href="/IDPPred/about/">About</a><br />
    </div>
{% endblock %}

templates/IDPPred/base.html
<!DOCTYPE html>
{% load staticfiles %} 
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>IDPPred - 
        {% block title_block %}
            Home
        {% endblock %}
    </title>
</head>
<body>
    {% block nav %}
    <span class="nav">
        <ul class="nav">
            <li class="picnav"><img class="nav" src="{% static 'images/logo3.png' %}" alt="Logo" /></li>
            <li class="nav" style="text-decoration: underline" ><a class="nav active" href="{% url 'IDPPred:index' %}">Home</a></li>
            <li class="nav"><a class="nav" href="{% url 'IDPPred:about' %}">About</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:help' %}">Help</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:sources' %}">Sources</a></li>
        </ul>
    </span>
    {% endblock %}
    
    {% block body_block %}
        default body
    {% endblock %}
</body>
</html>

templates/IDPPred/help.html
{% extends 'IDPPred/base.html' %}
{% load staticfiles %} 

{% block title_block %}
    About
{% endblock %}

{% block nav %}
    <span class="nav">
        <ul class="nav">
            <li class="picnav"><img class="nav" src="{% static 'images/logo3.png' %}" alt="Logo" /></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:index' %}">Home</a></li>
            <li class="nav"><a class="nav" href="{% url 'IDPPred:about' %}">About</a></li>
            <li class="nav" style="text-decoration: underline" ><a class="nav active" href="{% url 'IDPPred:help' %}">Help</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:sources' %}">Sources</a></li>
        </ul>
    </span>
    {% endblock %}


{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        hey there partner! <br />
    </div>
    <img src="{% static 'images/logo.png' %}" alt="Logo" />
    <div>
        <a href="/IDPPred/about/">About</a><br />
    </div>
{% endblock %}

templates/IDPPred/index.html
{% extends 'IDPPred/base.html' %}
{% load staticfiles %} 


{% block body_block %}
    <br>
    <br>
    <br>
    <br>
    <h2 >Input Sequence</h2>

    {% if GET %}
        <form action="{% url 'IDPPred:index' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    {% else %}
    <div>
        Key: <br>
        <div style="display: inline-block; color:red">
        High Disorder Chance ( Chance > 75% )
        </div><br>
        <div style="display: inline-block; color:orange">
            Medium Disorder Chance ( 50% < Chance > 75% )
        </div><br>
        <div style="display: inline-block; color:yellowgreen">
            Low Disorder Chance ( 25% < Chance > 50% )
        </div><br>
        <div style="display: inline-block; color:green">
            Very Low Disorder Chance ( < 25% )
        </div><br>
        <div style="display: inline-block; color:gray">
            No Prediction Gathered (First 7 and Last 7 Residues of Sequence)
        </div><br>
    </div>
        <br>
        {% if sequence_data.high %}
                <div style="display: inline-block; color:red">
                    <h2>Overall Sequence Prediction: {{sequence_data.class}} </h2>
                    <h1>Chance of Disorder Percentage : {{sequence_data.prediction}}% </h1>
                </div><br>
            {% elif sequence_data.med %}
                <div style="display: inline-block; color:orange">
                    <h2>Overall Sequence Prediction: {{sequence_data.class}} </h2>
                    <h1>Chance of Disorder Percentage: {{sequence_data.prediction}}% </h1>
                </div><br>
            {% elif sequence_data.neutral %}
                <div style="display: inline-block; color:grey">
                    <h2>Overall Sequence Prediction: {{sequence_data.class}} </h2>
                    <h1>Chance of Disorder Percentage: {{sequence_data.prediction}}% </h1>
                </div><br>
            {% elif sequence_data.low %}
                <div style="display: inline-block; color:yellowgreen">
                    <h2>Overall Sequence Prediction: {{sequence_data.class}} </h2>
                    <h1>Chance of Disorder Percentage: {{sequence_data.prediction}}% </h1>
                </div><br>
            {% elif sequence_data.verylow %}
                <div style="display: inline-block; color:green">
                    <h2>Overall Sequence Prediction: {{sequence_data.class}} </h2>
                    <h1>Chance of Disorder Percentage: {{sequence_data.prediction}}% </h1>
                </div><br>
        {%endif %}

        <h1> Residue Breakdown:</h1> <br>
        <div style="padding-left: 10%;padding-right: 10%;">
        {% for letter in letters %}
            {% if letter.high %}
                <div style="display: inline-block; color:red">
                    {{ letter.residue }}
                    <!--{{ letter.prediction }}-->
                </div>
            {% elif letter.med %}
                <div style="display: inline-block; color:orange">
                    {{ letter.residue }}
                    <!--{{ letter.prediction }}-->
                </div>
            {% elif letter.neutral %}
                <div style="display: inline-block; color:grey">
                    {{ letter.residue }}
                    <!--{{ letter.prediction }}-->
                </div>
            {% elif letter.low %}
                <div style="display: inline-block; color:yellowgreen">
                    {{ letter.residue }}
                    <!--{{ letter.prediction }}-->
                </div>
            {% elif letter.verylow %}
                <div style="display: inline-block; color:green">
                    {{ letter.residue }}
                    <!--{{ letter.prediction }}-->
                </div>
            {%endif %}
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/IDPPred/sources.html
{% extends 'IDPPred/base.html' %}
{% load staticfiles %} 

{% block title_block %}
    About
{% endblock %}

{% block nav %}
    <span class="nav">
        <ul class="nav">
            <li class="picnav"><img class="nav" src="{% static 'images/logo3.png' %}" alt="Logo" /></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:index' %}">Home</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:about' %}">About</a></li>
            <li class="nav" ><a class="nav" href="{% url 'IDPPred:help' %}">Help</a></li>
            <li class="nav" style="text-decoration: underline"><a class="nav active" href="{% url 'IDPPred:sources' %}">Sources</a></li>
        </ul>
    </span>
    {% endblock %}


{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        hey there partner! <br />
    </div>
    <img src="{% static 'images/logo.png' %}" alt="Logo" />
    <div>
        <a href="/IDPPred/about/">About</a><br />
    </div>
{% endblock %}